version: 2
jobs:
  build:
    docker:
      - image: python:3.6-jessie

    working_directory: ~/repo

    steps:
      - checkout
      - run: python3.6 -m pip install -r requirements.txt

      - run:
          name: start flask app
          command: python app.py
          background: true

      - run: pytest tests/
